# Generated by Django 2.2.6 on 2019-11-11 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GL_User',
            fields=[
                ('uid', models.IntegerField(primary_key=True, serialize=False, verbose_name='GitLab: ID пользователя')),
                ('name', models.CharField(max_length=255, verbose_name='GitLab: Имя')),
                ('p_user', models.CharField(max_length=255, verbose_name='GitLab: ***Parol***')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Локальный пользователь')),
            ],
            options={
                'verbose_name': 'GitLab Пользователь',
                'verbose_name_plural': 'GitLab Пользователи',
            },
        ),
    ]
