# Generated by Django 2.2.6 on 2019-11-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_remove_gl_project_creator'),
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gl_user',
            name='member',
            field=models.ManyToManyField(related_name='user_projects', to='projects_app.GL_Project', verbose_name='GitLab: Проекты'),
        ),
    ]
