# Generated by Django 2.2.6 on 2019-11-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_gl_user_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gl_user',
            name='member',
            field=models.ManyToManyField(null=True, related_name='user_projects', to='projects_app.GL_Project', verbose_name='GitLab: Проекты'),
        ),
    ]
