# Generated by Django 2.2.6 on 2019-11-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_auto_20191113_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gl_user',
            name='member',
            field=models.ManyToManyField(related_name='user_projects', to='projects_app.GL_Project', verbose_name='GitLab: Проекты'),
        ),
    ]
