# Generated by Django 2.2.6 on 2019-11-11 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gl_project',
            name='creator',
        ),
    ]
