# Generated by Django 2.2.6 on 2019-11-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_gl_project_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gl_project',
            name='creator',
        ),
    ]
