# Generated by Django 2.2.6 on 2019-11-13 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects_app', '0004_remove_gl_project_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='gl_project',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='GitLab: Создатель'),
            preserve_default=False,
        ),
    ]
